version: '3.1'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchmark
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchmark
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
    - "3307:3306"

  adminer:
    image: adminer
    ports:
      - 8081:8080